import type { NextPage } from "next";
import { InferGetServerSidePropsType, GetServerSideProps } from "next";

import Head from "next/head";
import { Header, HEADER_HEIGHT } from "components/Header";

import { getCV } from "shared/queries";
import { CV, ResponseBody } from "shared/types";
import { parseCvInfo } from "shared/utils";
import dynamic from "next/dynamic";
import { Alert } from "@mantine/core";
import { useRouter } from "next/router";

type ServerSideProps = {
  response: ResponseBody<CV>;
};
export const getServerSideProps: GetServerSideProps<ServerSideProps> = async (
  context
) => {
  const params = context.params;
  const id = params?.id;

  const { data: responseBody } = await getCV(id as string);
  return {
    props: {
      response: responseBody,
    }, // will be passed to the page component as props
  };
};

const PDFDocument = dynamic(() => import("components/PDF"), { ssr: false });

const CVPage: NextPage<ServerSideProps> = ({
  response,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const router = useRouter();
  const { id } = router.query;
  const info = parseCvInfo(response.data?.cvBody);
  return (
    <>
      <Head>
        <title>CV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>

      {response.data && info ? (
        <PDFDocument info={info} />
      ) : (
        <div
          style={{
            height: `calc(100vh - ${HEADER_HEIGHT}px)`,
          }}
          className="flex justify-center items-center"
        >
          <Alert title="Invalid ID" color="red">
            Cannot fetch CV with id: {id}
          </Alert>
        </div>
      )}
    </>
  );
};

export default CVPage;
