import type { NextPage } from "next";
import Head from "next/head";
import { useInitCVInfo, useSubscribeFbAuthState } from "shared/hooks";
import dynamic from "next/dynamic";
import { Header } from "components/Header";

const PDFDocument = dynamic(() => import("components/PDF"), { ssr: false });
const Test: NextPage = () => {
  useInitCVInfo();
  useSubscribeFbAuthState();

  return (
    <>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>

      <PDFDocument />
    </>
  );
};

export default Test;
