import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "components/Header";
import dynamic from "next/dynamic";

const DynamicMain = dynamic(() => import("components/Main"), { ssr: false });
const Home: NextPage = () => {
  
  return (
    <>
      <Head>
        <title>Hire me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
      <DynamicMain />
    </>
  );
};

export default Home;
