import type { NextPage } from "next";
import Head from "next/head";
import { useInitCVInfo, useSubscribeFbAuthState } from "shared/hooks";
import { MyDocument } from "components/PDF";

const Test: NextPage = () => {
  useInitCVInfo();
  useSubscribeFbAuthState();

  return (
    <>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MyDocument />
    </>
  );
};

export default Test;
