import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "components/Header";
import { useAtom } from "jotai";
import { accessTokenAtom, appUserAtom } from "shared/atoms";
import { useRouter } from "next/router";
import { useQuery } from "react-query";
import { getAllCVsByEmail } from "shared/queries";

const UserPage: NextPage = () => {
  const [user] = useAtom(appUserAtom);
  const [accessToken] = useAtom(accessTokenAtom);
  const router = useRouter();

  const { data } = useQuery(
    ["getAllCVs", user?.email],
    () => {
      if (user?.email) {
        return getAllCVsByEmail(user?.email);
      }
    },
    {
      enabled: !!user?.email && !!accessToken,
    }
  );
  return (
    <>
      <Head>
        <title>Hire me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
    </>
  );
};

export default UserPage;
