import { QueryClient } from "react-query";
import { NavCategoryType } from "./types";

export const NAV_BAR: NavCategoryType[] = [
  "TEMPLATE",
  "PROFILE",
  "EDUCATION",
  "WORK",
  "SKILLS",
  "PROJECTS",
  "AWARDS",
];

export const QUERY_CLIENT = new QueryClient();

export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;

export const APP_LOCAL_STORAGE_PREFIX = "HIRE_ME_";
export const CURRENT_NAV_BAR_LOCAL_STORAGE =
  APP_LOCAL_STORAGE_PREFIX + "NAV_BAR";

export const CV_INFO_LOCAL_STORAGE_KEYS: Record<NavCategoryType, string> = {
  TEMPLATE: APP_LOCAL_STORAGE_PREFIX + "TEMPLATE_INFO",
  PROFILE: APP_LOCAL_STORAGE_PREFIX + "PROFILE_INFO",
  EDUCATION: APP_LOCAL_STORAGE_PREFIX + "EDUCATION_INFO",
  WORK: APP_LOCAL_STORAGE_PREFIX + "WORK_INFO",
  SKILLS: APP_LOCAL_STORAGE_PREFIX + "SKILLS_INFO",
  PROJECTS: APP_LOCAL_STORAGE_PREFIX + "PROJECTS_INFO",
  AWARDS: APP_LOCAL_STORAGE_PREFIX + "AWARDS_INFO",
} as const;
